name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    permissions:
      actions: read
      contents: read

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: Kesin11/actions-timeline@v1

      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 🏗 Setup node env
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          check-latest: true
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: 👨🏻‍💻 Install dependencies
        run: npm ci

      - name: 👀 Run linter
        run: npm run lint

      - name: 🐷 Run Typecheck
        run: npm run typecheck
